### ISSUE TITLE
Add the when(), whenAnyTrait(), whenAllTraits() methods to IBuilder

### ISSUE THREAD

**Issue by webJose** [WJSoftware/wj-config#17]
# Purpose

The `when()` function will be a function that will bind the provided predicate function (a function that returns true if the data source must be added or false otherwise) to the last-added data source.  The predicate's signature will be:  `function(currentEnvironment: IEnvironmentDefinition): bool`.  This means that the predicate will receive the current environment as input.  This can only happen if the consumer of **wj-config** includes a call to the builder's `includeEnvironment()` function.  This conditional inclusion, however, could prove useful to someone at some point in time, so if the `includeEnvironment()` call is not made, let the predicate be executed by passing `null` as the current environment.

The `whenAllTraits()` and `whenAnyTrait()` methods will provide the consumer of the configuration builder the ability to specify a number of traits that must exist in the current environment definition object for the previously-added data source to qualify.  The former will require all listed traits to be present in the current environment definition object; the latter will be satisfied if any of the listed traits is found in the current environment object.

# Design

The functions will behave the same as the existing `name()` function used to give a name to the data source:  It must follow an `addXXX()` function or the `name()` function or an error is thrown.  Since now there are more than one function that apply to the last-added data source, the internal implementation needs  to be changed slightly.  There is a control Boolean value that tells the builder if the previous call was a call to add a data source.  Now `name()` and these new functions must not set the control variable.

The use of the functions `whenAnyTrait()` and `whenAllTraits()` require the use of the `includeEnvironment()` builder function.  The `build()` function will make sure there is an included environment object if any of the new functions are used.  Since the builder provides little enforcement on the order in which functions are called, `whenAnyTrait()` and `whenAllTraits()` are used, they must mark the mandatory nature for the envronment object somewhere internally so the call to `build()` can properly throw an error if the environment is not being included.

**Comment by NXPY123** [comment]
Hi! I saw your comment on my recent post([dev.to](https://dev.to/nxpy123/can-anyone-suggest-repositories-to-contribute-in-2o48)) asking for help on this issue and would like to contribute to resolving it. 

It would be really helpful if you could assign me the issue and guide me on how to proceed to resolve it!

**Comment by webJose** [comment]
Hello, yes.  Before I assign this to you, I would like to make sure that you read the Issue called **Project Overview** so you fully understand what all this is about.  I have also updated this task to reflect my current mind state. :-)  Now I want 3 functions, not just 2.

**Comment by NXPY123** [comment]
@webJose I have read the Project Overview and I believe I have gained some insight into the repository. From what I understand, both whenAnyTraits() and whenAllTraits() should be wrapper functions for when()? I'll start going through the codebase and testing out the module to further understand how it works. 

Also which branch should I be working on?

**Comment by webJose** [comment]
Yes, that is correct.  So `when()` is the core functionality.  It allows the consumer of the package to conditionally add any data source based on pretty much any condition they like.  As a commodity, if an environment object was added to the builder by using `includeEnvironment()` then said environment object will be passed along as the first parameter of the `when()` function.  At this point, the use of `includeEnvironment()` is optional.  `when()` will work regardless.

So, now that you have the core, simply create the trait-specific wrappers `whenAnyTraits()` and `whenAllTraits()`.  If a consumer of the package decides to use any of these, then the builder will be instructed to throw an error if `includeEnvironment()` was not called because traits are evaluated agains the current environment, so we **must** have the environment object now.  Makes sense?  Hopefully it does.

I don't know if you can add to the repo directly so I guess go ahead and fork it.  There are 3 branches, one of which is named `Environment_Traits` that contains the initial work I made for this feature.  I would suggest you take advantage of that work.  Afterwards, we'll merge to the `Version_2` branch and make a Release Candidate version.

Cheers and thanks.

**Comment by webJose** [comment]
One note for clarification:  I know I have written in different places `whenAnyTraits` and `whenAnyTrait`.  Apologies for the ambiguity.  I want the singular form:  `whenAnyTrait`, because only one matching trait is need to fulfill the predicate.

**Comment by NXPY123** [comment]
@webJose Is the module an ES Module now? Because when I try to use require to include the module it throws the error:

> Error [ERR_REQUIRE_ESM]: require() of ES Module [module_path] not supported

When I searched the error the answers said it might be because it is an ESM module and doesn't support require anymore.
[StackOverflow Question](https://stackoverflow.com/questions/69081410/error-err-require-esm-require-of-es-module-not-supported)

When I use import wjConfig the config obtained when console logged is a Builder Object:
```javascript
Builder {
  _dataSources: [],
  _envSource: undefined,
  _urlData: undefined,
  _lastCallWasDsAdd: false
}
```

Is this the output I'm supposed to obtain?

**Comment by webJose** [comment]
Yes, @NXPY123, wj-config v2 is ES Modules.  In the readme you can find the way it can be used in NodeJS with CommonJS, but I personally recommend to you ES Modules.

**Comment by webJose** [comment]
Regarding output:  **After awaiting the `build()` call**, you get an object with the properties you specified in your data sources.

**Comment by NXPY123** [comment]
@webJose Yes that worked! Thank you! 

Are the steps in the readme not for wj-config@2.0.0-beta.2? This is the version I installed by doing npm install and the index.js file doesn't seem to have the constructor specified in the config.js file in the readme example:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/46917698/196181256-6006ba0b-baa5-4a23-978d-052e688a54ff.png">

Also the Builder class in Builder.js file doesn't seem to implement the IBuilder interface: 
<img width="664" alt="image" src="https://user-images.githubusercontent.com/46917698/196181143-cdc1caeb-6fde-4ca2-a7ad-44cae988602d.png">

The module seems to be functioning fine if I pass the JSON to the DataSource using addJSON.

```javascript
const mainConfig =  loadJsonFile('./config/config.json', true);
const envConfig =  loadJsonFile(`./config/config.Development.json`, false);
config.addJson(JSON.stringify(mainConfig));
config.addJson(JSON.stringify(envConfig));

config.build().then((config) => {
    console.log(config);
});

```

The above code works fine and logs the merged JSON

Is this a problem with the package that I installed? When I checked the branches there doesn't seem to be one with files that match the ones installed. The Version_2 and Environment_Traits branch have everything required but they're written in TypeScript. Will that be a problem since I don't have experience using TypeScript before?

**Comment by webJose** [comment]
Hi.  The Readme in the main branch is still for v1.x.  Read the ReadMe in the `Version_2` branch, which is the one you need.

Without checking the code, I would say it is not possible for the `Builder` class to not implement the `IBuilder` interface (unless you take into account the partial work in the `Environment_Traits` branch, perhaps) because I would not have built and published something `tsc` would have thrown an error for.  Since `tsc` compiled without errors, I can only conclude that, by the time I published Beta 2, the `Builder` class was correctly implementing the `IBuilder` interface.  So most likely is due to work in progress?

Also, no need to stringify.  You should be able to just do `config.addObject(mainConfig)` and skip that step.

The source code is **TypeScript**, so it must be written in TypeScript.  I would say, no worries if you have never done so before.  I had never done TypeScript before this project.  It is not very difficult to learn.  After a couple of days of reading the Microsoft website and you'll be up and running.

**Comment by NXPY123** [comment]
Sorry I couldn't work on the issue the past week since I had exams. When I tried to use the github branch as dependency([medium.com/@jonchurch/…](https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a)), it gave this error:

```
npm ERR! Cannot read properties of undefined (reading 'spec')

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/neeraj_py/.npm/_logs/2022-11-10T06_37_38_314Z-debug-0.log
```
I tried looking it up but the solutions didn't work. Do you know how to resolve it?

**Comment by webJose** [comment]
@NXPY123 lNo, I don't use that method to simulate the module installation.  Instead, I build the TypeScript to some directory and then set up a `wj-config` Symbolic Link folder inside whatever `node_modules` folder I want to test with.

**Comment by webJose** [comment]
Deployed in RC0.
